"""Pydantic models for the Persome HTTP REST API."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, model_validator

# Capture payloads contain a rendered AX tree and, optionally, one JPEG.  The
# native producer normally stays well below these limits.  Explicit ceilings
# protect the HTTP process before the payload reaches OCR/encryption/disk.
MAX_CAPTURE_JSON_BYTES = 12 * 1024 * 1024
MAX_CAPTURE_IMAGE_B64_CHARS = 8 * 1024 * 1024
MAX_CAPTURE_METADATA_BYTES = 128 * 1024
MAX_CAPTURE_AX_TREE_BYTES = 8 * 1024 * 1024


def _json_size(value: Any) -> int:
    import json

    return len(json.dumps(value, ensure_ascii=False, separators=(",", ":")).encode("utf-8"))


# ─── Generic envelope ──────────────────────────────────────────────────────


class ApiResponse(BaseModel):
    """Common response envelope for the local runtime API."""

    success: bool = Field(default=True, description="Whether the request succeeded")
    data: dict | list | str | None = Field(default=None, description="Response payload")


class ModelPing(BaseModel):
    stage: str = Field(description="LLM stage name, such as timeline, reducer, or classifier")
    model: str = Field(description="Configured model name")
    ok: bool = Field(description="Whether the stage model is reachable")
    latency_ms: int | None = Field(default=None, description="Ping latency in milliseconds")
    error: str | None = Field(default=None, description="Error returned when the ping fails")


class CaptureIngestBody(BaseModel):
    """One capture frame pushed by a trusted Swift producer.

    The Swift process owns Accessibility and Screen Recording permissions and
    supplies the AX tree plus an optional focused-window screenshot. The daemon
    performs enrichment and persistence. Fields align with the native
    ``_build_capture`` output and degrade safely when optional data is absent.
    """

    timestamp: str | None = Field(
        default=None,
        max_length=64,
        description="ISO 8601 capture time; generated by the server when omitted",
    )
    trigger: dict[str, Any] | None = Field(
        default=None,
        description="Trigger metadata: {event_type, bundle_id, window_title, details?}",
    )
    window_meta: dict[str, Any] = Field(
        default_factory=dict, description="{app_name, title, bundle_id}"
    )
    ax_tree: dict[str, Any] | None = Field(
        default=None,
        description="Raw AX tree: {apps -> windows -> elements}; omission means AX is unavailable",
    )
    ax_metadata: dict[str, Any] | None = Field(default=None, description="AX capture metadata")
    screenshot: dict[str, Any] | None = Field(
        default=None,
        description=(
            "{image_base64, mime_type, width, height}; plaintext in transit and encrypted "
            "at rest according to server configuration"
        ),
    )
    ocr_jpeg_b64: str | None = Field(
        default=None,
        max_length=MAX_CAPTURE_IMAGE_B64_CHARS,
        description="Base64 focused-window JPEG for local OCR when AX text is insufficient",
    )
    ocr_tier: str | None = Field(
        default=None,
        max_length=32,
        description="Per-capture OCR tier override; uses configuration when omitted",
    )

    @model_validator(mode="after")
    def _bounded_payload(self) -> CaptureIngestBody:
        for label, value in (
            ("trigger", self.trigger),
            ("window_meta", self.window_meta),
            ("ax_metadata", self.ax_metadata),
        ):
            if value is not None and _json_size(value) > MAX_CAPTURE_METADATA_BYTES:
                raise ValueError(f"{label} exceeds {MAX_CAPTURE_METADATA_BYTES} bytes")

        if self.ax_tree is not None and _json_size(self.ax_tree) > MAX_CAPTURE_AX_TREE_BYTES:
            raise ValueError(f"ax_tree exceeds {MAX_CAPTURE_AX_TREE_BYTES} bytes")

        if self.screenshot is not None:
            image = self.screenshot.get("image_base64")
            if image is not None and (
                not isinstance(image, str) or len(image) > MAX_CAPTURE_IMAGE_B64_CHARS
            ):
                raise ValueError(
                    f"screenshot.image_base64 exceeds {MAX_CAPTURE_IMAGE_B64_CHARS} characters"
                )

        if _json_size(self.model_dump()) > MAX_CAPTURE_JSON_BYTES:
            raise ValueError(f"capture payload exceeds {MAX_CAPTURE_JSON_BYTES} bytes")
        return self
